name = "RobustMean"
uuid = "1f212c10-5119-456f-85ee-3680502e4796"
authors = ["David Métivier <46794064+dmetivie@users.noreply.github.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
